url:
    issues: https://github.com/jaymegordo/guesttracker/issues/new/choose
    docs: ''

ModelPaths:
    FortHills:
        980E: 1. 980E Trucks
        930E: 2. 930E Trucks
        HD1500: 3. HD1500
    BaseMine:
        980E: 1. Trucks/2. 980E
        930E: 1. Trucks/1. 930E
        HD1500: 1. Trucks/3. HD1500

ComponentMap:
    WM: Wheel Motor
    ENG: Engine
    RAD: Radiator
    FSUSP: Front Suspension
    RSUSP: Rear Suspension
    SPIND: Spindle
    SA: Steering Arm
    MTA: Main Traction Alternator
    HC: Hoist Cylinder
    SC: Steering Cylinder
    PB: Park Brake

Email: jaymegordo@gmail.com

color:
    bg:
        maroon: '#9e2121'
        lightred: '#F8696B'
        lightyellow: '#FFFFCC'
        lightgreen: '#99FF99'
        lightorange: '#ffbf7a'
        lightblue: '#CCECFF'
        lightpurple: '#e8aeff'
        darkgreen: '#6db56d'
        darkblue: '#6494b0'
        medblue: '#569cd6'
        goodgreen: '#C6EFCE'
        tan: '#e2c091'
        good: '#c6e3ef'
        bad: '#FFC7CE'
        greyrow: '#E4E4E4'
        yellowrow: '#ffff64'
        darkyellow: '#cccc4e'
        darkgrey: '#999999'
        navyblue: '#244062'
        skyblue: '#91c3ff'
        orange: '#f08a37'
        bgdark: '#19232d'
        black: 'black'
    text:
        goodgreen: '#006100'
        good: '#003961'
        bad: '#9C0006'
        black: 'black'
        white: 'white'
    thead: '#244062'

Lists:
    WarrantyType:
        - 'Yes'
        - 'No'
        - PRP
        - RAMP
        - Service
        - Parts
    TrueFalse:
        - 'True'
        - 'False'

# Convert title to tablename > can select from views but not update them
TableName:
    Class: # map class name to title
        Accounts: Accounts
        ChargeItems: Charge Items
        Charges: Charges
        Classes: Classes
        Customers: Customers
        PackageUnits: Package Units
        Packages: Packages
        Reservations: Reservations
        Units: Units
    Select:
        Placeholder: Placeholder
    Update:
        Placeholder: Placeholder


# Table header conversion
Headers:
    Reservations:
        uid: uid
        Customer Name: customer_name
        Status: status
        Unit Assignments: unit_assignments
        Arrival Date: arrival_date
        Departure Date: departure_date
        Date Made: date_made
        Cancel Date: cancel_date
        Num Persons: num_persons
        Deposit Amount: deposit_amount
        Deposit Date: deposit_date
        Notes: notes
        Requests: requests
    Customers:
        uid: uid
        Name: name
        Email: email
        First Contact: first_contact
        Last Contact: last_contact
        Home Phone: home_phone
        Work Phone: work_phone
        Alt Phone: alt_phone
        Company: company
        Addr1: addr1
        City: city
        State: state
        Zip: zip
        Country: country
        Addr2: addr2
        Notes: notes
        International: international
        Relationship: relationship
        Source: source
        Name First: name_first
        Name Last: name_last
    Accounts:
        uid: uid
        Name: name
        Number: number
        Tax Rate: tax_rate
    Charge Items:
        uid: uid
        Name: name
        Pre Tax Price: pre_tax_price
        Tax Rate: tax_rate
        Post Tax Price: post_tax_price
        Includes Tax: includes_tax
    Charges:
        uid: uid
        Customer Name: customer_name
        Kind: kind
        Sub Kind: sub_kind
        Item: item
        Charge Date: charge_date
        Posting Date: posting_date
        Quantity: quantity
        Pre Tax Price: pre_tax_price
        Post Tax Price: post_tax_price
        Total Amount: total_amount
        Tax1 Rate: tax1_rate
        Tax2 Rate: tax2_rate
        Total Tax1: total_tax1
        Total Tax2: total_tax2
        Includes Tax: includes_tax
        Discount: discount
    Classes:
        uid: uid
        Name: name
    Package Units:
        uid: uid
    Packages:
        uid: uid
        Name: name
        Description: description
        Rate: rate
        Account Name: account_name
    Units:
        uid: uid
        Name: name
        Abbr: abbr
        Max Persons: max_persons
        Active: active
        Class Name: class_name

Platform:
    mac:
        font size: 15
    win:
        font size: 11
